(()=>{"use strict";
const CFG=window.LUCKY_CONFIG||{},START=1000,$=(q,r=document)=>r.querySelector(q),$$=(q,r=document)=>[...r.querySelectorAll(q)],fmt=n=>Math.max(0,Math.floor(Number(n)||0)).toLocaleString();
let auth=null,db=null,currentUser=null,isAdmin=false,mode="guest",unsubscribe=null,busy=false,currentGame="wolf",currentPull="lucky",bet=10,players=[];
let wolfBuild=[0,0,0];
const guest=JSON.parse(localStorage.getItem("LLV4guest")||"null")||{coins:START,stats:{plays:0,totalWon:0,biggestWin:0}};
const games={
wolf:{title:"WOLF & PIGGY FORTUNE",subtitle:"Build houses. Trigger the saw wheel. Survive the wolf finale.",symbols:["🐷","🏠","🌾","🪚","🧱","🐺","💰","⭐"],weights:[24,20,16,14,10,7,5,4],reels:5,cls:"wolfCabinet",rules:[["3/4/5 matching","3× / 8× / 20× bet"],["🪚 on 1,3,5","Saw Wheel feature"],["🏠 symbols","Advance house construction"],["Completed houses","Straw → wood → brick"],["Wolf finale","Awards coin feature"],["💰 x3+","Piggy Bank bonus"]]},
sky:{title:"SPIN THE SKY WHEEL",subtitle:"Wheel symbols on reels 1, 3 and 5 trigger the overhead bonus.",symbols:["🎟️","💵","💎","⭐","☁️","🎡","🔔"],weights:[25,22,18,14,10,6,5],reels:5,cls:"skyCabinet",rules:[["3/4/5 matching","3× / 7× / 18× bet"],["🎡 on reels 1,3,5","Outer Sky Wheel"],["Credit wedge","May trigger inner wheel"],["Inner wheel","2×, 3×, 4×, 5× or respin"],["BONUS wedge","Money Catch pick bonus"],["Jackpot wedges","Mini / Minor / Major"]]},
classic:{title:"LEGENDARY 3-REEL",subtitle:"Classic center-line wins.",symbols:["🍒","🔔","🍀","7️⃣","💎"],weights:[34,27,20,13,6],reels:3,cls:"classicCabinet",rules:[["💎💎💎","100× bet"],["7️⃣7️⃣7️⃣","50× bet"],["🍀🍀🍀","25× bet"],["Any pair","2× bet"]]}
};
const pulls={lucky:{title:"LUCKY REVEAL",desc:"Match symbols across six windows.",cost:20,s:["🍀","💎","7️⃣","🔔","🍒"],rules:["3 matches = 80","4 = 200","5 = 500","6 = 2,000"]},gold:{title:"GOLD RUSH",desc:"Reveal money bags for instant prizes.",cost:25,s:["💰","⛏️","🪨","✨","🪙"],rules:["1 💰 = 50","2 = 150","3 = 400","4+ = 1,500"]},party:{title:"PARTY POP",desc:"Match party symbols or reveal three 🎉.",cost:25,s:["🎈","🎁","🪩","🎉","🎊"],rules:["3 matches = 100","4 = 250","3 🎉 = 500","5+ = 1,200"]}};
function rnd(n){let a=new Uint32Array(1);crypto.getRandomValues(a);return a[0]%n}function pick(g){let t=g.weights.reduce((a,b)=>a+b,0),r=rnd(t);for(let i=0;i<g.symbols.length;i++){if(r<g.weights[i])return g.symbols[i];r-=g.weights[i]}return g.symbols[0]}
function state(){return mode==="cloud"&&window.cloudPlayer?window.cloudPlayer:guest}function saveGuest(){localStorage.setItem("LLV4guest",JSON.stringify(guest))}
function render(){let s=state();$("#coinBalance").textContent=fmt(s.coins);$("#machineBalance").textContent=fmt(s.coins);$("#statPlays").textContent=fmt(s.stats?.plays||0);$("#statWon").textContent=fmt(s.stats?.totalWon||0);$("#statBiggest").textContent=fmt(s.stats?.biggestWin||0)}
async function setState(n){if(mode==="cloud"&&currentUser&&db){await db.collection("users").doc(currentUser.uid).update({coins:Math.max(0,Math.floor(n.coins)),stats:n.stats,lastSeen:firebase.firestore.FieldValue.serverTimestamp()})}else{guest.coins=n.coins;guest.stats=n.stats;saveGuest();render()}}
async function applyResult(cost,win){let s=state();if((s.coins||0)<cost)throw Error("Not enough coins.");await setState({coins:(s.coins||0)-cost+win,stats:{plays:(s.stats?.plays||0)+1,totalWon:(s.stats?.totalWon||0)+win,biggestWin:Math.max(s.stats?.biggestWin||0,win)}})}
function toast(t){let e=$("#toast");e.textContent=t;e.classList.add("show");clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove("show"),1800)}
function show(id){$$(".screen").forEach(s=>s.classList.remove("active"));$("#"+id).classList.add("active");scrollTo(0,0)}
function counts(a){return a.reduce((m,x)=>(m[x]=(m[x]||0)+1,m),{})}
function setupGame(k){currentGame=k;let g=games[k];$("#slotTitle").textContent=g.title;$("#slotSubtitle").textContent=g.subtitle;$("#slotCabinet").className="slotCabinet "+g.cls;$("#skyFeatureArea").classList.toggle("hidden",k!=="sky");$("#wolfProgress").classList.toggle("hidden",k!=="wolf");$("#featurePanel").classList.add("hidden");$("#slotMessage").textContent="READY TO SPIN";buildReels();updateWolfMeters();show("slot")}
function buildReels(){let g=games[currentGame],box=$("#reels");box.className="reels "+(g.reels===3?"three":"");box.innerHTML="";for(let c=0;c<g.reels;c++){let col=document.createElement("div");col.className="reelCol";for(let r=0;r<3;r++){let d=document.createElement("div");d.className="symbol";d.textContent=g.symbols[(c+r)%g.symbols.length];col.appendChild(d)}box.appendChild(col)}}
function updateWolfMeters(){$("#house1").textContent=wolfBuild[0]+"/3";$("#house2").textContent=wolfBuild[1]+"/3";$("#house3").textContent=wolfBuild[2]+"/3"}
function markBuildStages(grid){if(currentGame!=="wolf")return;let cols=$$(".reelCol");for(let c=0;c<grid.length;c++)for(let r=0;r<3;r++){let el=$$(".symbol",cols[c])[r];el.classList.remove("build1","build2","build3");if(grid[c][r]==="🏠"){let stage=wolfBuild[r];if(stage>0)el.classList.add("build"+Math.min(stage,3))}}}
async function spin(){if(busy)return;if(state().coins<bet)return toast("Not enough coins.");busy=true;$("#spinBtn").disabled=true;$("#featurePanel").classList.add("hidden");$("#winMeter").textContent="0";let g=games[currentGame],cols=$$(".reelCol");cols.forEach(c=>c.classList.add("spinning"));let grid=Array.from({length:g.reels},()=>Array.from({length:3},()=>pick(g)));
for(let c=0;c<cols.length;c++){await new Promise(r=>setTimeout(r,260+c*115));cols[c].classList.remove("spinning");$$(".symbol",cols[c]).forEach((e,r)=>e.textContent=grid[c][r])}
markBuildStages(grid);let middle=grid.map(c=>c[1]),cc=counts(middle),best=Math.max(...Object.values(cc)),win=0,msg="";
if(currentGame==="classic"){let[a,b,c]=middle;if(a===b&&b===c)win=bet*({"💎":100,"7️⃣":50,"🍀":25,"🔔":15,"🍒":10}[a]||0);else if(a===b||b===c||a===c)win=bet*2}else win=bet*({3:3,4:8,5:20}[best]||0);
if(currentGame==="wolf"){let all=grid.flat(),ac=counts(all);
  let houses=ac["🏠"]||0;if(houses){for(let i=0;i<Math.min(3,houses);i++){let row=rnd(3);wolfBuild[row]=Math.min(3,wolfBuild[row]+1)}updateWolfMeters();markBuildStages(grid)}
  if(grid[0].includes("🪚")&&grid[2].includes("🪚")&&grid[4].includes("🪚")){let b=await sawWheel();win+=b;msg="SAW WHEEL • "}
  if(wolfBuild.every(x=>x===3)){let b=await wolfFinale();win+=b;wolfBuild=[0,0,0];updateWolfMeters();msg="WOLF FINALE • "}
  if((ac["💰"]||0)>=3){let b=bet*(8+rnd(13));win+=b;showFeature("PIGGY BANK BONUS","🐷💰",`The piggy bank paid +${fmt(b)} coins.`);msg="PIGGY BANK • "}
}
if(currentGame==="sky"&&grid[0].includes("🎡")&&grid[2].includes("🎡")&&grid[4].includes("🎡")){let b=await skyWheelBonus();win+=b;msg="SKY WHEEL • "}
try{await applyResult(bet,win);$("#winMeter").textContent=fmt(win);$("#slotMessage").textContent=win?`${msg}WIN ${fmt(win)} COINS`:"NO WIN — SPIN AGAIN";if(win)toast("✨ WIN "+fmt(win)+" COINS")}catch(e){toast(e.message)}busy=false;$("#spinBtn").disabled=false}
function showFeature(title,icons,text){let p=$("#featurePanel");p.innerHTML=`<h3>${title}</h3><div class="big">${icons}</div><p>${text}</p>`;p.classList.remove("hidden")}
async function sawWheel(){showFeature("BUZZ SAW FEATURE","🪚🎡🐷","The saw wheel is selecting a house upgrade...");await new Promise(r=>setTimeout(r,700));let upgrade=1+rnd(3);for(let i=0;i<upgrade;i++){let row=rnd(3);wolfBuild[row]=Math.min(3,wolfBuild[row]+1)}updateWolfMeters();let b=bet*(4+rnd(9));showFeature("HOUSE UPGRADE","🏠➡️🏡",`${upgrade} house section${upgrade>1?"s":""} upgraded. +${fmt(b)} coins.`);return b}
async function wolfFinale(){showFeature("WOLF FINALE","🐺💨🏠🐷","All three houses are complete. The wolf is testing them...");await new Promise(r=>setTimeout(r,900));let tiers=[10,15,20,30,50],m=tiers[rnd(tiers.length)],b=bet*m;showFeature("BRICK HOUSE SURVIVES!","🧱🏠✨",`The pigs protected the prize: ${m}× bet = +${fmt(b)} coins.`);return b}
async function skyWheelBonus(){let outer=$("#outerWheel");$("#skyFeatureText").textContent="SPINNING THE SKY WHEEL…";outer.classList.add("spin");await new Promise(r=>setTimeout(r,1850));outer.classList.remove("spin");let wedges=["credit200","mini","credit500","major","credit1000","bonus","credit250","minor"],w=wedges[rnd(wedges.length)];
if(w==="mini"){let b=bet*20;$("#skyFeatureText").textContent=`MINI JACKPOT! +${fmt(b)}`;return b}
if(w==="minor"){let b=bet*50;$("#skyFeatureText").textContent=`MINOR JACKPOT! +${fmt(b)}`;return b}
if(w==="major"){let b=bet*100;$("#skyFeatureText").textContent=`MAJOR JACKPOT! +${fmt(b)}`;return b}
if(w==="bonus"){return await moneyCatchBonus()}
let credits={credit200:200,credit250:250,credit500:500,credit1000:1000}[w];$("#skyFeatureText").textContent=`CREDIT WEDGE ${credits} — INNER WHEEL ACTIVATED`;return await innerWheelBonus(credits)}
async function innerWheelBonus(base){let wrap=$("#innerWheelWrap"),wheel=$("#innerWheel");wrap.classList.remove("hidden");wheel.classList.add("spin");await new Promise(r=>setTimeout(r,1350));wheel.classList.remove("spin");let outcomes=[2,3,4,5,"respin"],o=outcomes[rnd(outcomes.length)];if(o==="respin"){$("#skyFeatureText").textContent="RESPIN! Spinning the outer wheel again…";wrap.classList.add("hidden");return await skyWheelBonus()}let b=base*o;$("#skyFeatureText").textContent=`INNER WHEEL ${o}× • +${fmt(b)} COINS`;wrap.classList.add("hidden");return b}
async function moneyCatchBonus(){let p=$("#featurePanel");p.classList.remove("hidden");p.innerHTML='<h3>MONEY CATCH BONUS</h3><p>Pick 3 floating prizes.</p><div class="pickGrid"></div>';let grid=$(".pickGrid",p),picked=0,total=0;return await new Promise(resolve=>{for(let i=0;i<6;i++){let btn=document.createElement("button"),val=bet*[2,3,5,8,10,15][rnd(6)];btn.textContent="☁️";btn.onclick=()=>{if(btn.disabled)return;btn.disabled=true;btn.textContent=fmt(val);total+=val;picked++;if(picked===3){$("#skyFeatureText").textContent=`MONEY CATCH TOTAL +${fmt(total)} COINS`;setTimeout(()=>resolve(total),450)}};grid.appendChild(btn)}})}
function setupPull(k){currentPull=k;let p=pulls[k];$("#pullTitle").textContent=p.title;$("#pullDesc").textContent=p.desc;$("#ticketCost").textContent=p.cost+" COINS";$("#pullRules").innerHTML=p.rules.map(x=>`<span>${x}</span>`).join("");resetTicket();show("pull")}
function resetTicket(){let g=$("#ticketGrid");g.innerHTML="";for(let i=0;i<6;i++){let d=document.createElement("div");d.className="tab covered";d.textContent="PULL";g.appendChild(d)}$("#ticketResult").textContent="BUY A TICKET TO PLAY"}
async function buyTicket(){if(busy)return;let p=pulls[currentPull];if(state().coins<p.cost)return toast("Not enough coins.");busy=true;let arr=[],prize=0;
if(currentPull==="gold"){let n=rnd(100)<38?1+rnd(4):0;arr=Array(n).fill("💰");while(arr.length<6)arr.push(p.s[1+rnd(p.s.length-1)]);prize=n>=4?1500:n===3?400:n===2?150:n===1?50:0}
else{while(arr.length<6)arr.push(p.s[rnd(p.s.length)]);let c=counts(arr),best=Math.max(...Object.values(c));if(currentPull==="party"&&(c["🎉"]||0)>=3)prize=500;else prize=currentPull==="lucky"?({3:80,4:200,5:500,6:2000}[best]||0):(best>=5?1200:best===4?250:best===3?100:0)}
let tabs=$$(".tab");for(let i=0;i<6;i++){await new Promise(r=>setTimeout(r,130));tabs[i].classList.remove("covered");tabs[i].textContent=arr[i]}await applyResult(p.cost,prize);$("#ticketResult").textContent=prize?`WINNER! +${fmt(prize)} COINS`:"NO PRIZE — TRY AGAIN";busy=false}
function showRules(){let g=games[currentGame];$("#rulesTitle").textContent=g.title;$("#rulesBody").innerHTML=g.rules.map(x=>`<div><span>${x[0]}</span><b>${x[1]}</b></div>`).join("");$("#rulesModal").classList.remove("hidden")}
function cloudReady(){let c=CFG.FIREBASE_CONFIG||{};return c.apiKey&&!String(c.apiKey).startsWith("PASTE_")}
async function initCloud(){if(!cloudReady())return;firebase.initializeApp(CFG.FIREBASE_CONFIG);auth=firebase.auth();db=firebase.firestore();auth.onAuthStateChanged(async u=>{currentUser=u;isAdmin=!!u&&String(u.email||"").toLowerCase()===String(CFG.ADMIN_EMAIL||"").toLowerCase();$("#adminNav").classList.toggle("hidden",!isAdmin);$("#signedOutView").classList.toggle("hidden",!!u);$("#signedInView").classList.toggle("hidden",!u);if(unsubscribe)unsubscribe();if(u){mode="cloud";$("#profileName").textContent=u.displayName||"Player";$("#profileEmail").textContent=u.email||"";let ref=db.collection("users").doc(u.uid),s=await ref.get();if(!s.exists)await ref.set({displayName:u.displayName||"Player",email:u.email||"",coins:START,stats:{plays:0,totalWon:0,biggestWin:0}});unsubscribe=ref.onSnapshot(s=>{window.cloudPlayer=s.data();render()})}else{mode="guest";window.cloudPlayer=null;render()}})}
async function loadPlayers(){if(!isAdmin)return;let s=await db.collection("users").limit(100).get();players=s.docs.map(d=>({id:d.id,...d.data()}));renderPlayers()}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function renderPlayers(){let q=$("#playerSearch").value.toLowerCase();$("#playerList").innerHTML="";players.filter(p=>!q||(p.displayName||"").toLowerCase().includes(q)||(p.email||"").toLowerCase().includes(q)).forEach(p=>{let d=document.createElement("div");d.className="playerRow";d.innerHTML=`<b>${esc(p.displayName||"Player")}</b> • 🪙 ${fmt(p.coins)}<small><br>${esc(p.email||"")}</small><div class="adjust"><input type="number" min="1" value="100"><button>+ Add</button><button>− Remove</button></div>`;let input=$("input",d),bs=$$("button",d);bs[0].onclick=()=>adjust(p.id,Math.abs(+input.value||0));bs[1].onclick=()=>adjust(p.id,-Math.abs(+input.value||0));$("#playerList").appendChild(d)})}
async function adjust(id,n){let ref=db.collection("users").doc(id);await db.runTransaction(async t=>{let s=await t.get(ref);t.update(ref,{coins:Math.max(0,(+s.data().coins||0)+n)})});toast((n>0?"Added ":"Removed ")+fmt(Math.abs(n))+" coins");loadPlayers()}
$$("[data-open-slot]").forEach(b=>b.onclick=()=>setupGame(b.dataset.openSlot));$$("[data-pull]").forEach(b=>b.onclick=()=>setupPull(b.dataset.pull));$$(".back").forEach(b=>b.onclick=()=>show("home"));$$("[data-nav]").forEach(b=>b.onclick=()=>{let n=b.dataset.nav;if(n==="home")show("home");else if(n==="slot")setupGame(currentGame);else if(n==="pull")setupPull(currentPull);else if(n==="admin"&&isAdmin){show("admin");loadPlayers()}});
$("#spinBtn").onclick=spin;$("#betDown").onclick=()=>{bet=bet===50?25:bet===25?10:10;$("#betMeter").textContent=bet;$("#spinCost").textContent=bet+" COINS"};$("#betUp").onclick=()=>{bet=bet===10?25:bet===25?50:50;$("#betMeter").textContent=bet;$("#spinCost").textContent=bet+" COINS"};$("#buyTicketBtn").onclick=()=>{resetTicket();buyTicket()};$("#rulesBtn").onclick=showRules;
$("#accountBtn").onclick=()=>$("#accountModal").classList.remove("hidden");$$("[data-close]").forEach(b=>b.onclick=()=>$("#"+b.dataset.close+"Modal").classList.add("hidden"));
$("#signInBtn").onclick=async()=>{try{await auth.signInWithEmailAndPassword($("#loginEmail").value,$("#loginPassword").value);$("#accountModal").classList.add("hidden")}catch(e){$("#authMsg").textContent=e.message}};
$("#signUpBtn").onclick=async()=>{try{let c=await auth.createUserWithEmailAndPassword($("#signupEmail").value,$("#signupPassword").value);await c.user.updateProfile({displayName:$("#signupName").value});await db.collection("users").doc(c.user.uid).set({displayName:$("#signupName").value,email:$("#signupEmail").value,coins:START,stats:{plays:0,totalWon:0,biggestWin:0}});$("#accountModal").classList.add("hidden")}catch(e){$("#authMsg").textContent=e.message}};
$("#signOutBtn").onclick=()=>auth&&auth.signOut();$("#refreshPlayers").onclick=loadPlayers;$("#playerSearch").oninput=renderPlayers;
setupGame("wolf");show("home");render();initCloud();
})();