(()=>{"use strict";
const C=window.LUCKY_CONFIG||{},START=1000,$=(q,r=document)=>r.querySelector(q),$$=(q,r=document)=>[...r.querySelectorAll(q)],fmt=n=>Math.max(0,Math.floor(+n||0)).toLocaleString();
let auth=null,db=null,user=null,admin=false,mode="guest",unsub=null,busy=false,bet=10,game="wolf",pull="lucky",players=[];
const guest=JSON.parse(localStorage.getItem("LLguest")||"null")||{coins:START,stats:{plays:0,totalWon:0,biggestWin:0}};
const games={
wolf:{title:"WOLF & PIGGY FORTUNE",sub:"Build the houses. Watch for the wolf.",symbols:["🐷","🏠","🌾","🪚","🧱","🐺","💰"],weights:[25,22,18,14,11,7,3],cls:"wolfMachine",reels:5,rules:[["3 matching","3× bet"],["4 matching","8× bet"],["5 matching","20× bet"],["3+ 🏠","Piggy House feature"],["3+ 🐺","Wolf feature"],["3+ 💰","Piggy Bank bonus"]]},
sky:{title:"SPIN THE SKY WHEEL",sub:"Land 3 clouds to spin the giant prize wheel.",symbols:["🎟️","💵","💎","⭐","☁️","🎡"],weights:[28,24,19,15,10,4],cls:"skyMachine",reels:5,rules:[["3 matching","3× bet"],["4 matching","7× bet"],["5 matching","18× bet"],["3+ ☁️","Sky Wheel bonus"],["Wheel","2×–50× bet"]]},
classic:{title:"LEGENDARY 3-REEL",sub:"Classic line wins and big multipliers.",symbols:["🍒","🔔","🍀","7️⃣","💎"],weights:[34,27,20,13,6],cls:"classicMachine",reels:3,rules:[["💎💎💎","100× bet"],["7️⃣7️⃣7️⃣","50× bet"],["🍀🍀🍀","25× bet"],["Any pair","2× bet"]]}
};
const pulls={
lucky:{title:"LUCKY REVEAL",desc:"Match symbols across six windows.",cost:20,s:["🍀","💎","7️⃣","🔔","🍒"],rules:["3 matches = 80","4 = 200","5 = 500","6 = 2,000"]},
gold:{title:"GOLD RUSH",desc:"Find money bags for instant prizes.",cost:25,s:["💰","⛏️","🪨","✨","🪙"],rules:["1 💰 = 50","2 = 150","3 = 400","4+ = 1,500"]},
party:{title:"PARTY POP",desc:"Match party symbols or reveal 3 party pop symbols.",cost:25,s:["🎈","🎁","🪩","🎉","🎊"],rules:["3 matches = 100","4 = 250","3 🎉 = 500","5+ = 1,200"]}
};
function rnd(n){let a=new Uint32Array(1);crypto.getRandomValues(a);return a[0]%n}function pick(g){let t=g.weights.reduce((a,b)=>a+b),r=rnd(t);for(let i=0;i<g.symbols.length;i++){if(r<g.weights[i])return g.symbols[i];r-=g.weights[i]}return g.symbols[0]}
function state(){return mode==="cloud"&&window.cloudPlayer?window.cloudPlayer:guest}function save(){localStorage.setItem("LLguest",JSON.stringify(guest))}
function render(){let s=state();$("#coinBalance").textContent=fmt(s.coins);$("#machineBalance").textContent=fmt(s.coins);$("#statPlays").textContent=fmt(s.stats?.plays||0);$("#statWon").textContent=fmt(s.stats?.totalWon||0);$("#statBiggest").textContent=fmt(s.stats?.biggestWin||0)}
async function setState(n){if(mode==="cloud"&&user&&db)await db.collection("users").doc(user.uid).update({coins:Math.max(0,Math.floor(n.coins)),stats:n.stats,lastSeen:firebase.firestore.FieldValue.serverTimestamp()});else{guest.coins=n.coins;guest.stats=n.stats;save();render()}}
async function result(cost,win){let s=state();if(s.coins<cost)throw Error("Not enough coins.");await setState({coins:s.coins-cost+win,stats:{plays:(s.stats?.plays||0)+1,totalWon:(s.stats?.totalWon||0)+win,biggestWin:Math.max(s.stats?.biggestWin||0,win)}})}
function toast(x){let e=$("#toast");e.textContent=x;e.classList.add("show");setTimeout(()=>e.classList.remove("show"),1800)}
function screen(n){$$(".screen").forEach(x=>x.classList.remove("active"));$(`#${n}Screen`).classList.add("active");scrollTo(0,0)}
function counts(a){return a.reduce((m,x)=>(m[x]=(m[x]||0)+1,m),{})}
function setupGame(k){game=k;let g=games[k];$("#gameTitle").textContent=g.title;$("#gameSub").textContent=g.sub;$("#machine").className="slotMachine "+g.cls;$("#wheelArea").classList.toggle("hidden",k!=="sky");$("#feature").classList.add("hidden");$("#message").textContent="READY TO SPIN";buildReels();screen("slot")}
function buildReels(){let g=games[game],box=$("#reels");box.className="reels "+(g.reels===3?"three":"");box.innerHTML="";for(let c=0;c<g.reels;c++){let col=document.createElement("div");col.className="reelCol";for(let r=0;r<3;r++){let s=document.createElement("div");s.className="symbol";s.textContent=g.symbols[(c+r)%g.symbols.length];col.appendChild(s)}box.appendChild(col)}}
async function spin(){if(busy)return;if(state().coins<bet)return toast("Not enough coins.");busy=true;$("#spinBtn").disabled=true;$("#feature").classList.add("hidden");$("#winMeter").textContent="0";let g=games[game],cols=$$(".reelCol");cols.forEach(x=>x.classList.add("spinning"));let grid=Array.from({length:g.reels},()=>Array.from({length:3},()=>pick(g)));
for(let c=0;c<cols.length;c++){await new Promise(r=>setTimeout(r,250+c*110));cols[c].classList.remove("spinning");$$(".symbol",cols[c]).forEach((e,r)=>e.textContent=grid[c][r])}
let middle=grid.map(c=>c[1]),ct=counts(middle),best=Math.max(...Object.values(ct)),win=0,msg="";
if(game==="classic"){let[a,b,c]=middle;if(a===b&&b===c)win=bet*({"💎":100,"7️⃣":50,"🍀":25,"🔔":15,"🍒":10}[a]||0);else if(a===b||b===c||a===c)win=bet*2}
else win=bet*({3:3,4:8,5:20}[best]||0);
let all=grid.flat(),ac=counts(all);
if(game==="wolf"){if((ac["🏠"]||0)>=3){let b=bet*(3+rnd(8));win+=b;$("#feature").innerHTML='<b>🐷 PIGGY HOUSE FEATURE!</b><div class="houses"><span>🏚️</span><span>🏠</span><span>🏡</span><span>🏠</span><span>🏡</span></div><p>The pigs upgraded their houses! +'+fmt(b)+' coins</p>';$("#feature").classList.remove("hidden");msg="HOUSE FEATURE • "}
if((ac["🐺"]||0)>=3){let b=bet*(5+rnd(11));win+=b;$("#feature").innerHTML='<b>🐺 WOLF FEATURE!</b><div class="houses"><span>💨</span><span>🐺</span><span>🏠</span><span>💨</span><span>🐷</span></div><p>The wolf feature awarded +'+fmt(b)+' coins!</p>';$("#feature").classList.remove("hidden");msg="WOLF FEATURE • "}
if((ac["💰"]||0)>=3){let b=bet*(8+rnd(13));win+=b;msg="PIGGY BANK • "}}
if(game==="sky"&&(ac["☁️"]||0)>=3){let mult=[2,3,5,8,10,15,25,50][rnd(8)];let b=bet*mult;$("#wheel").classList.add("spinWheel");$("#wheelText").textContent="SPINNING THE SKY WHEEL…";await new Promise(r=>setTimeout(r,1750));$("#wheel").classList.remove("spinWheel");$("#wheelText").textContent=`WHEEL LANDED ON ${mult}× • +${fmt(b)} COINS`;win+=b;msg="SKY WHEEL BONUS • "}
try{await result(bet,win);$("#winMeter").textContent=fmt(win);$("#message").textContent=win?`${msg}WIN ${fmt(win)} COINS`:"NO WIN — SPIN AGAIN";if(win)toast("✨ WIN "+fmt(win)+" COINS")}catch(e){toast(e.message)}busy=false;$("#spinBtn").disabled=false}
function setupPull(k){pull=k;let p=pulls[k];$("#pullTitle").textContent=p.title;$("#pullDesc").textContent=p.desc;$("#ticketCost").textContent=p.cost+" COINS";$("#pullRules").innerHTML=p.rules.map(x=>`<span>${x}</span>`).join("");resetTicket();screen("pull")}
function resetTicket(){let t=$("#ticket");t.innerHTML="";for(let i=0;i<6;i++){let d=document.createElement("div");d.className="tab covered";d.textContent="PULL";t.appendChild(d)}$("#ticketResult").textContent="BUY A TICKET TO PLAY"}
async function buy(){if(busy)return;let p=pulls[pull];if(state().coins<p.cost)return toast("Not enough coins.");busy=true;let arr=[],prize=0;if(pull==="gold"){let n=rnd(100)<38?1+rnd(4):0;arr=Array(n).fill("💰");while(arr.length<6)arr.push(p.s[1+rnd(p.s.length-1)]);prize=n>=4?1500:n===3?400:n===2?150:n===1?50:0}else{while(arr.length<6)arr.push(p.s[rnd(p.s.length)]);let c=counts(arr),best=Math.max(...Object.values(c));if(pull==="party"&&(c["🎉"]||0)>=3)prize=500;else prize=pull==="lucky"?({3:80,4:200,5:500,6:2000}[best]||0):(best>=5?1200:best===4?250:best===3?100:0)}
arr.sort(()=>rnd(3)-1);let tabs=$$(".tab");for(let i=0;i<6;i++){await new Promise(r=>setTimeout(r,130));tabs[i].classList.remove("covered");tabs[i].textContent=arr[i]}await result(p.cost,prize);$("#ticketResult").textContent=prize?`WINNER! +${fmt(prize)} COINS`:"NO PRIZE — TRY ANOTHER";busy=false}
function rules(){let g=games[game];$("#rulesTitle").textContent=g.title;$("#rulesBody").innerHTML=g.rules.map(x=>`<div><span>${x[0]}</span><b>${x[1]}</b></div>`).join("");$("#rulesModal").classList.remove("hidden")}
function cloudOK(){let c=C.FIREBASE_CONFIG||{};return c.apiKey&&!String(c.apiKey).startsWith("PASTE_")}
async function initCloud(){if(!cloudOK())return;firebase.initializeApp(C.FIREBASE_CONFIG);auth=firebase.auth();db=firebase.firestore();auth.onAuthStateChanged(async u=>{user=u;admin=!!u&&String(u.email||"").toLowerCase()===String(C.ADMIN_EMAIL||"").toLowerCase();$("#adminNav").classList.toggle("hidden",!admin);$("#signedOut").classList.toggle("hidden",!!u);$("#signedIn").classList.toggle("hidden",!u);if(unsub)unsub();if(u){mode="cloud";$("#profileName").textContent=u.displayName||"Player";$("#profileEmail").textContent=u.email||"";let ref=db.collection("users").doc(u.uid),s=await ref.get();if(!s.exists)await ref.set({displayName:u.displayName||"Player",email:u.email||"",coins:START,stats:{plays:0,totalWon:0,biggestWin:0}});unsub=ref.onSnapshot(s=>{window.cloudPlayer=s.data();render()})}else{mode="guest";window.cloudPlayer=null;render()}})}
async function loadPlayers(){if(!admin)return;let s=await db.collection("users").limit(100).get();players=s.docs.map(d=>({id:d.id,...d.data()}));renderPlayers()}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function renderPlayers(){let q=$("#playerSearch").value.toLowerCase();$("#playerList").innerHTML="";players.filter(p=>!q||(p.displayName||"").toLowerCase().includes(q)||(p.email||"").toLowerCase().includes(q)).forEach(p=>{let d=document.createElement("div");d.className="player";d.innerHTML=`<b>${esc(p.displayName||"Player")}</b> • 🪙 ${fmt(p.coins)}<small><br>${esc(p.email||"")}</small><div class="adjust"><input type="number" value="100" min="1"><button>+ ADD</button><button>− REMOVE</button></div>`;let inp=$("input",d),bs=$$("button",d);bs[0].onclick=()=>adjust(p.id,Math.abs(+inp.value||0));bs[1].onclick=()=>adjust(p.id,-Math.abs(+inp.value||0));$("#playerList").appendChild(d)})}
async function adjust(id,n){let ref=db.collection("users").doc(id);await db.runTransaction(async t=>{let s=await t.get(ref);t.update(ref,{coins:Math.max(0,(+s.data().coins||0)+n)})});toast((n>0?"Added ":"Removed ")+fmt(Math.abs(n))+" coins");loadPlayers()}
$$("[data-game]").forEach(b=>b.onclick=()=>setupGame(b.dataset.game));$$("[data-pull]").forEach(b=>b.onclick=()=>setupPull(b.dataset.pull));$$(".back").forEach(b=>b.onclick=()=>screen("lobby"));$$("[data-nav]").forEach(b=>b.onclick=()=>{let n=b.dataset.nav;if(n==="lobby")screen("lobby");if(n==="slot")setupGame(game);if(n==="pull")setupPull(pull);if(n==="admin"&&admin){screen("admin");loadPlayers()}});$("#spinBtn").onclick=spin;$("#betDown").onclick=()=>{bet=bet===50?25:bet===25?10:10;$("#betMeter").textContent=bet;$("#spinCost").textContent=bet+" COINS"};$("#betUp").onclick=()=>{bet=bet===10?25:bet===25?50:50;$("#betMeter").textContent=bet;$("#spinCost").textContent=bet+" COINS"};$("#buyTicket").onclick=()=>{resetTicket();buy()};$("#rulesBtn").onclick=rules;$("#accountBtn").onclick=()=>$("#accountModal").classList.remove("hidden");$(".x").onclick=()=>$("#accountModal").classList.add("hidden");$(".rulesX").onclick=()=>$("#rulesModal").classList.add("hidden");$("#signIn").onclick=async()=>{try{await auth.signInWithEmailAndPassword($("#email").value,$("#password").value);$("#accountModal").classList.add("hidden")}catch(e){$("#authMsg").textContent=e.message}};$("#signUp").onclick=async()=>{try{let c=await auth.createUserWithEmailAndPassword($("#newEmail").value,$("#newPassword").value);await c.user.updateProfile({displayName:$("#newName").value});await db.collection("users").doc(c.user.uid).set({displayName:$("#newName").value,email:$("#newEmail").value,coins:START,stats:{plays:0,totalWon:0,biggestWin:0}});$("#accountModal").classList.add("hidden")}catch(e){$("#authMsg").textContent=e.message}};$("#signOut").onclick=()=>auth&&auth.signOut();$("#refreshPlayers").onclick=loadPlayers;$("#playerSearch").oninput=renderPlayers;
setupGame("wolf");screen("lobby");render();initCloud();
})();